# !/bin/bash

export SERVICE_PATH=${SERVICE_PATH:=/opt/backend}

export SERVICE_DOMAIN_NAME=${SERVICE_DOMAIN_NAME:=demo.com}

export DATABASE_NAME=${DATABASE_NAME:=demo}
export DATABASE_USER=${DATABASE_USER:=demo}
export DATABASE_PASSWORD=${DATABASE_PASSWORD:=demo}
export DATABASE_HOST=${DATABASE_HOST:=database}
export DATABASE_PORT=${DATABASE_PORT:=5432}

export WSGI_PROCESSES=${WSGI_PROCESSES:=10}

export NGINX_PORT=${NGINX_PORT:=80}

export NGINX_WORKER_PROCESS=${NGINX_WORKER_PROCESS:=1}
export NGINX_KEEP_ALIVE_TIMEOUT=${NGINX_KEEP_ALIVE_TIMEOUT:=65}
export NGINX_CLIENT_MAX_BODY_SIZE=${NGINX_CLIENT_MAX_BODY_SIZE:=75M}
